### NOTAS

In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("202309-7E PYTHON FUNDAMENTALS FOR DATA SCIENCE grades - 11_19_2023, 06_38 PM.csv")

In [4]:
df = df.drop(11)
df = df.reset_index(drop=True)

In [5]:
df.shape

(12, 27)

In [6]:
df

,First Name,Last Name,Email Address,Examen Final,Points,Feedback,Tarea-07,Points.1,Feedback.1,Tarea-06,Points.2,Feedback.2,Tarea-05,Points.3,Feedback.3,Tarea-04,Points.4,Feedback.4,Tarea-03,Points.5,Feedback.5,Tarea - 02,Points.6,Feedback.6,Tarea-01,Points.7,Feedback.7
0,Cesar Miguel,Cubas Cabanillas,X202032208@cibertec.edu.pe,19.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-2\n8-2\n9-2\n10-1,4.5,5,"esta parte esta repetitiva, se podria automati...",5.0,5,NaN,5.0,5,NaN,0.0,5,NaN,5.0,5,"EstÃ¡ en orden, sin embargo, continuemos siguie...",1.5,2,Nice,1.5,2,NaN
1,Giancarlo Paul,Koo Farfan,X202037163@cibertec.edu.pe,18.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-0\n8-2\n9-2\n10-2,4.5,5,esta bien pero me hubiera gustado ver un data ...,5.0,5,NaN,5.0,5,NaN,3.5,5,NaN,5.0,5,NaN,1.5,2,NaN,1.5,2,NaN
2,Jorge,Campos Campos,x041638@cibertec.edu.pe,20.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-2\n8-2\n9-2\n10-2,4.5,5,"muy bien, tendriamos que mejorar ese grafico\n...",4.0,5,NaN,3.5,5,NaN,5.0,5,Perfecto,5.0,5,Perfecto ðŸ‘Œ,1.5,2,Nice,1.5,2,NaN
3,Jose Antonio,Espinoza Aldave,X008024197@cibertec.edu.pe,14.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-0\n8-0\n9-0\n10-2,5.0,5,hay que mejorar este grafico por el resto esta...,3.5,5,NaN,3.5,5,NaN,3.5,5,NaN,5.0,5,- solo un # para comentarios\n- cuidemos los e...,2.0,2,NaN,2.0,2,NaN
4,Luis Anselmo,Alcala Rodriguez,X202062825@cibertec.edu.pe,18.0,20,1-0\n2-2\n3-2\n4-2\n5-2\n6-2\n7-2\n8-2\n9-2\n10-2,5.0,5,Excelente Luis no sabia que se podia hacer vid...,5.0,5,Perfecto Luis,5.0,5,NaN,4.0,5,Creo que falta un problema?,4.5,5,"Muy bien, falta un poco mÃ¡s de markdown, para ...",1.5,2,Nice,1.5,2,NaN
5,Maria Angela,Huisa Martinez,x218013@cibertec.edu.pe,20.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-2\n8-2\n9-2\n10-2,5.0,5,muy bien,5.0,5,NaN,5.0,5,NaN,5.0,5,perfecto,5.0,5,Perfecto,1.5,2,NaN,1.5,2,NaN
6,Martin Jose,Escobar Fernandez,X000001783@cibertec.edu.pe,13.0,20,1-0\n2-2\n3-2\n4-2\n5-2\n6-2\n7-0\n8-2\n9-1\n10-0,0.0,5,NaN,0.0,5,NaN,0.0,5,NaN,5.0,5,get_ipython().system('pip install pandas') \ni...,5.0,5,- solo un # para los comentarios\n- en el prim...,1.5,2,NaN,1.5,2,NaN
7,Milton David,Malca Capcha,X202062826@cibertec.edu.pe,20.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-2\n8-2\n9-2\n10-2,5.0,5,muy bien,5.0,5,NaN,5.0,5,NaN,5.0,5,perfecto,5.0,5,- python tambiÃ©n tiene tipado\n- continuemos s...,2.0,2,Nice,1.5,2,NaN
8,Olga Dina,Suarez Avelino,X200212793@cibertec.edu.pe,16.0,20,1-2\n2-2\n3-2\n4-2\n5-0\n6-2\n7-2\n8-0\n9-2\n10-2,4.0,5,NaN,5.0,5,NaN,5.0,5,NaN,5.0,5,perfecto,5.0,5,Esta perfecto,2.0,2,Perfecto,1.5,2,NaN
9,Rene Antoine,Carrion Galiano,X202072048@cibertec.edu.pe,12.0,20,1-2\n2-2\n3-2\n4-2\n5-0\n#P5_SOL\nprop = float...,0.0,5,NaN,2.5,5,NaN,5.0,5,NaN,0.0,5,NaN,4.5,5,Esta muy bien pero quizas no sea una buena opc...,2.0,2,NaN,1.5,2,NaN
10,RHOLF ALONSO,JARA QUINTANA,X202329597@cibertec.edu.pe,16.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-1\n8-0\n9-2\n10-1,4.5,5,esta bien pero me hubiera gustado ver como un ...,5.0,5,NaN,5.0,5,NaN,5.0,5,Perfecto,4.5,5,NaN,1.5,2,NaN,1.5,2,It's OK but out of time
11,Victor Alfredo,Alzamora Medina,x113181@cibertec.edu.pe,20.0,20,1-2\n2-2\n3-2\n4-2\n5-2\n6-2\n7-2\n8-2\n9-2\n10-2,5.0,5,"Preciso y claro, super python.",0.0,5,NaN,5.0,5,NaN,5.0,5,Perfecto,5.0,5,Muy muy bueno tanto del lado del cÃ³digo como d...,2.0,2,Perfecto!!!,2.0,2,Perfecto

In [7]:
column_names_list = list(df.columns)
column_names_list

['First Name',
 'Last Name',
 'Email Address',
 'Examen Final',
 'Points',
 'Feedback',
 'Tarea-07',
 'Points.1',
 'Feedback.1',
 'Tarea-06',
 'Points.2',
 'Feedback.2',
 'Tarea-05',
 'Points.3',
 'Feedback.3',
 'Tarea-04',
 'Points.4',
 'Feedback.4',
 'Tarea-03',
 'Points.5',
 'Feedback.5',
 'Tarea - 02',
 'Points.6',
 'Feedback.6',
 'Tarea-01',
 'Points.7',
 'Feedback.7']

In [8]:
column_name_mapping = {
    'Points': 'final_score', 
    'Points.1': 'score_7', 
    'Points.2': 'score_6',
    'Points.3': 'score_5', 
    'Points.4': 'score_4', 
    'Points.5': 'score_3',
    'Points.6': 'score_2',
    'Points.7': 'score_1',
    'Tarea - 02': 'Tarea-02',
    'Examen Final': 'Evaluacion Final (EF)',
}

In [9]:
df = df.rename(columns=column_name_mapping)

In [10]:
columns_to_keep = [
    'First Name', 'Last Name',
    'Evaluacion Final (EF)', 'final_score',
    'Tarea-07', 'score_7', 
    'Tarea-06', 'score_6', 
    'Tarea-05', 'score_5', 
    'Tarea-04', 'score_4', 
    'Tarea-03', 'score_3', 
    'Tarea-02', 'score_2', 
    'Tarea-01', 'score_1']

In [11]:
notas_df = df[columns_to_keep]
notas_df

,First Name,Last Name,Evaluacion Final (EF),final_score,Tarea-07,score_7,Tarea-06,score_6,Tarea-05,score_5,Tarea-04,score_4,Tarea-03,score_3,Tarea-02,score_2,Tarea-01,score_1
0,Cesar Miguel,Cubas Cabanillas,19.0,20,4.5,5,5.0,5,5.0,5,0.0,5,5.0,5,1.5,2,1.5,2
1,Giancarlo Paul,Koo Farfan,18.0,20,4.5,5,5.0,5,5.0,5,3.5,5,5.0,5,1.5,2,1.5,2
2,Jorge,Campos Campos,20.0,20,4.5,5,4.0,5,3.5,5,5.0,5,5.0,5,1.5,2,1.5,2
3,Jose Antonio,Espinoza Aldave,14.0,20,5.0,5,3.5,5,3.5,5,3.5,5,5.0,5,2.0,2,2.0,2
4,Luis Anselmo,Alcala Rodriguez,18.0,20,5.0,5,5.0,5,5.0,5,4.0,5,4.5,5,1.5,2,1.5,2
5,Maria Angela,Huisa Martinez,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,1.5,2,1.5,2
6,Martin Jose,Escobar Fernandez,13.0,20,0.0,5,0.0,5,0.0,5,5.0,5,5.0,5,1.5,2,1.5,2
7,Milton David,Malca Capcha,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2
8,Olga Dina,Suarez Avelino,16.0,20,4.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2
9,Rene Antoine,Carrion Galiano,12.0,20,0.0,5,2.5,5,5.0,5,0.0,5,4.5,5,2.0,2,1.5,2
10,RHOLF ALONSO,JARA QUINTANA,16.0,20,4.5,5,5.0,5,5.0,5,5.0,5,4.5,5,1.5,2,1.5,2
11,Victor Alfredo,Alzamora Medina,20.0,20,5.0,5,0.0,5,5.0,5,5.0,5,5.0,5,2.0,2,2.0,2

In [19]:
notas_df.loc[9, 'Tarea-04'] = 3.5
# notas_df.loc[5, 'Tarea-04'] = 5

In [20]:
# Calculate the average for the first 5 tasks
average_first_5 = notas_df[["Tarea-07", "Tarea-06", "Tarea-05", "Tarea-04", "Tarea-03"]].mean(axis=1)

# Convert the average to a grade base 20
grade_first_5 = average_first_5 * 20 / 5

# Add a new column named `grade_first_5` to the DataFrame using .loc
notas_df.loc[:, "Evaluacion Tareas (ET)"] = grade_first_5

In [21]:
notas_df

,First Name,Last Name,Evaluacion Final (EF),final_score,Tarea-07,score_7,Tarea-06,score_6,Tarea-05,score_5,Tarea-04,score_4,Tarea-03,score_3,Tarea-02,score_2,Tarea-01,score_1,Evaluacion Tareas (ET),Asistencia Practicas (PP),Promedio Final (PF)
0,Cesar Miguel,Cubas Cabanillas,19.0,20,4.5,5,5.0,5,5.0,5,0.0,5,5.0,5,1.5,2,1.5,2,15.6,15.0,17.18
1,Giancarlo Paul,Koo Farfan,18.0,20,4.5,5,5.0,5,5.0,5,3.5,5,5.0,5,1.5,2,1.5,2,18.4,15.0,17.52
2,Jorge,Campos Campos,20.0,20,4.5,5,4.0,5,3.5,5,5.0,5,5.0,5,1.5,2,1.5,2,17.6,15.0,18.28
3,Jose Antonio,Espinoza Aldave,14.0,20,5.0,5,3.5,5,3.5,5,3.5,5,5.0,5,2.0,2,2.0,2,16.4,20.0,15.92
4,Luis Anselmo,Alcala Rodriguez,18.0,20,5.0,5,5.0,5,5.0,5,4.0,5,4.5,5,1.5,2,1.5,2,18.8,15.0,17.64
5,Maria Angela,Huisa Martinez,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,1.5,2,1.5,2,20.0,15.0,19.00
6,Martin Jose,Escobar Fernandez,13.0,20,0.0,5,0.0,5,0.0,5,5.0,5,5.0,5,1.5,2,1.5,2,8.0,15.0,11.90
7,Milton David,Malca Capcha,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2,20.0,17.5,19.50
8,Olga Dina,Suarez Avelino,16.0,20,4.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2,19.2,17.5,17.26
9,Rene Antoine,Carrion Galiano,12.0,20,0.0,5,2.5,5,5.0,5,3.5,5,4.5,5,2.0,2,1.5,2,12.4,17.5,13.34
10,RHOLF ALONSO,JARA QUINTANA,16.0,20,4.5,5,5.0,5,5.0,5,5.0,5,4.5,5,1.5,2,1.5,2,19.2,15.0,16.76
11,Victor Alfredo,Alzamora Medina,20.0,20,5.0,5,0.0,5,5.0,5,5.0,5,5.0,5,2.0,2,2.0,2,16.0,20.0,18.80

In [22]:
# Calculate the average for the first 2 tasks
average_first_2 = notas_df[["Tarea-02", "Tarea-01"]].mean(axis=1)

# Convert the average to a grade base 20
grade_first_2 = average_first_2 * 20 / 2

# Add a new column named `PP` to the DataFrame using .loc to avoid the warning
notas_df.loc[:, "Asistencia Practicas (PP)"] = grade_first_2

In [23]:
notas_df

,First Name,Last Name,Evaluacion Final (EF),final_score,Tarea-07,score_7,Tarea-06,score_6,Tarea-05,score_5,Tarea-04,score_4,Tarea-03,score_3,Tarea-02,score_2,Tarea-01,score_1,Evaluacion Tareas (ET),Asistencia Practicas (PP),Promedio Final (PF)
0,Cesar Miguel,Cubas Cabanillas,19.0,20,4.5,5,5.0,5,5.0,5,0.0,5,5.0,5,1.5,2,1.5,2,15.6,15.0,17.18
1,Giancarlo Paul,Koo Farfan,18.0,20,4.5,5,5.0,5,5.0,5,3.5,5,5.0,5,1.5,2,1.5,2,18.4,15.0,17.52
2,Jorge,Campos Campos,20.0,20,4.5,5,4.0,5,3.5,5,5.0,5,5.0,5,1.5,2,1.5,2,17.6,15.0,18.28
3,Jose Antonio,Espinoza Aldave,14.0,20,5.0,5,3.5,5,3.5,5,3.5,5,5.0,5,2.0,2,2.0,2,16.4,20.0,15.92
4,Luis Anselmo,Alcala Rodriguez,18.0,20,5.0,5,5.0,5,5.0,5,4.0,5,4.5,5,1.5,2,1.5,2,18.8,15.0,17.64
5,Maria Angela,Huisa Martinez,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,1.5,2,1.5,2,20.0,15.0,19.00
6,Martin Jose,Escobar Fernandez,13.0,20,0.0,5,0.0,5,0.0,5,5.0,5,5.0,5,1.5,2,1.5,2,8.0,15.0,11.90
7,Milton David,Malca Capcha,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2,20.0,17.5,19.50
8,Olga Dina,Suarez Avelino,16.0,20,4.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2,19.2,17.5,17.26
9,Rene Antoine,Carrion Galiano,12.0,20,0.0,5,2.5,5,5.0,5,3.5,5,4.5,5,2.0,2,1.5,2,12.4,17.5,13.34
10,RHOLF ALONSO,JARA QUINTANA,16.0,20,4.5,5,5.0,5,5.0,5,5.0,5,4.5,5,1.5,2,1.5,2,19.2,15.0,16.76
11,Victor Alfredo,Alzamora Medina,20.0,20,5.0,5,0.0,5,5.0,5,5.0,5,5.0,5,2.0,2,2.0,2,16.0,20.0,18.80

In [24]:
notas_df.loc[:, 'Promedio Final (PF)'] = ((notas_df['Asistencia Practicas (PP)'] * 0.20) +
                                           (notas_df['Evaluacion Tareas (ET)'] * 0.30) +
                                           (notas_df['Evaluacion Final (EF)'] * 0.50)).round(2)

In [25]:
notas_df

,First Name,Last Name,Evaluacion Final (EF),final_score,Tarea-07,score_7,Tarea-06,score_6,Tarea-05,score_5,Tarea-04,score_4,Tarea-03,score_3,Tarea-02,score_2,Tarea-01,score_1,Evaluacion Tareas (ET),Asistencia Practicas (PP),Promedio Final (PF)
0,Cesar Miguel,Cubas Cabanillas,19.0,20,4.5,5,5.0,5,5.0,5,0.0,5,5.0,5,1.5,2,1.5,2,15.6,15.0,17.18
1,Giancarlo Paul,Koo Farfan,18.0,20,4.5,5,5.0,5,5.0,5,3.5,5,5.0,5,1.5,2,1.5,2,18.4,15.0,17.52
2,Jorge,Campos Campos,20.0,20,4.5,5,4.0,5,3.5,5,5.0,5,5.0,5,1.5,2,1.5,2,17.6,15.0,18.28
3,Jose Antonio,Espinoza Aldave,14.0,20,5.0,5,3.5,5,3.5,5,3.5,5,5.0,5,2.0,2,2.0,2,16.4,20.0,15.92
4,Luis Anselmo,Alcala Rodriguez,18.0,20,5.0,5,5.0,5,5.0,5,4.0,5,4.5,5,1.5,2,1.5,2,18.8,15.0,17.64
5,Maria Angela,Huisa Martinez,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,1.5,2,1.5,2,20.0,15.0,19.00
6,Martin Jose,Escobar Fernandez,13.0,20,0.0,5,0.0,5,0.0,5,5.0,5,5.0,5,1.5,2,1.5,2,8.0,15.0,11.90
7,Milton David,Malca Capcha,20.0,20,5.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2,20.0,17.5,19.50
8,Olga Dina,Suarez Avelino,16.0,20,4.0,5,5.0,5,5.0,5,5.0,5,5.0,5,2.0,2,1.5,2,19.2,17.5,17.26
9,Rene Antoine,Carrion Galiano,12.0,20,0.0,5,2.5,5,5.0,5,3.5,5,4.5,5,2.0,2,1.5,2,12.4,17.5,13.22
10,RHOLF ALONSO,JARA QUINTANA,16.0,20,4.5,5,5.0,5,5.0,5,5.0,5,4.5,5,1.5,2,1.5,2,19.2,15.0,16.76
11,Victor Alfredo,Alzamora Medina,20.0,20,5.0,5,0.0,5,5.0,5,5.0,5,5.0,5,2.0,2,2.0,2,16.0,20.0,18.80

In [110]:
notas_df.to_csv("notas_finales_21_11_2023.csv")